import { Patient, VitalSigns, ConsciousnessLevel, NeoVitalSigns, ServiceType } from '../types';
import { calculateNEWS } from './newsScore';
import { generateAIInsights } from './aiAnalysis';

function rand(min: number, max: number, decimals = 0): number {
  const v = Math.random() * (max - min) + min;
  return decimals > 0 ? parseFloat(v.toFixed(decimals)) : Math.round(v);
}

function generateVitalHistory(
  baseHR: number,
  baseSBP: number,
  baseSpo2: number,
  baseRR: number,
  baseTemp: number,
  baseGlycemia: number,
  consciousness: ConsciousnessLevel,
  count = 20
): VitalSigns[] {
  const vitals: VitalSigns[] = [];
  const now = Date.now();
  for (let i = count - 1; i >= 0; i--) {
    vitals.push({
      heartRate: Math.max(30, Math.min(200, baseHR + rand(-8, 8))),
      systolicBP: Math.max(60, Math.min(240, baseSBP + rand(-10, 10))),
      diastolicBP: Math.max(40, Math.min(130, Math.round(baseSBP * 0.65) + rand(-5, 5))),
      spo2: Math.max(70, Math.min(100, baseSpo2 + rand(-2, 2))),
      respiratoryRate: Math.max(4, Math.min(40, baseRR + rand(-3, 3))),
      temperature: Math.max(34, Math.min(42, baseTemp + rand(-3, 3, 1))),
      glycemia: Math.max(0.6, Math.min(5.0, parseFloat((baseGlycemia + rand(-30, 30, 1) / 100).toFixed(2)))),
      consciousness,
      timestamp: now - i * 5 * 60 * 1000,
    });
  }
  return vitals;
}

function generateNeoVitalHistory(
  baseHR: number,
  baseSpo2: number,
  baseRR: number,
  baseTemp: number,
  weight: number,
  isPreemie: boolean,
  apgarAt5min: number,
  count = 20
): NeoVitalSigns[] {
  const vitals: NeoVitalSigns[] = [];
  const now = Date.now();
  const gestationalAge = isPreemie ? rand(28, 36) : rand(38, 40);

  for (let i = count - 1; i >= 0; i--) {
    vitals.push({
      heartRate: Math.max(100, Math.min(160, baseHR + rand(-10, 10))),
      systolicBP: Math.max(50, Math.min(100, isPreemie ? 55 + rand(-5, 5) : 70 + rand(-5, 5))),
      diastolicBP: Math.max(30, Math.min(70, isPreemie ? 35 + rand(-4, 4) : 45 + rand(-4, 4))),
      spo2: Math.max(85, Math.min(100, baseSpo2 + rand(-2, 2))),
      respiratoryRate: Math.max(30, Math.min(70, baseRR + rand(-5, 5))),
      temperature: Math.max(36.0, Math.min(38.0, baseTemp + rand(-2, 2, 1))),
      glycemia: Math.max(0.6, Math.min(2.5, parseFloat((rand(50, 150, 0) / 18 / 5).toFixed(2)))),
      consciousness: 'Alert',
      weight: weight,
      isPreemie: isPreemie,
      apgarAt5min: apgarAt5min,
      gestationalAge: gestationalAge,
      timestamp: now - i * 5 * 60 * 1000,
    });
  }
  return vitals as NeoVitalSigns[];
}

function makeDevices(types: Array<{ type: any; name: string; days: number; status: any }>): any[] {
  return types.map((d, i) => ({
    id: `dev-${i}`,
    name: d.name,
    type: d.type,
    status: d.status,
    detail: d.status === 'warning' ? 'Vérification requise' : d.status === 'error' ? 'Intervention nécessaire' : 'Fonctionnement normal',
    insertedDays: d.days,
    riskLevel: d.days > 5 ? 'high' : d.days > 3 ? 'medium' : 'low',
  }));
}

function makeBio(results: Array<{ name: string; value: string; unit: string; status: any }>): any[] {
  const today = new Date().toLocaleDateString('fr-FR');
  return results.map((r) => ({ ...r, date: today }));
}

const emptyNews = { total: 0, respiratoryRate: 0, spo2: 0, temperature: 0, systolicBP: 0, heartRate: 0, consciousness: 0, risk: 'low' as const, interpretation: '' };

export function createPatientsByService(service: ServiceType): Patient[] {
  if (service === 'reanimation') return createReanimationPatients();
  if (service === 'soinsIntensifs') return createSoinsIntensifPatients();
  if (service === 'dechocage') return createDechocagePatients();
  if (service === 'neonatologie') return createNeonatologiePatients();
  return [];
}

function createReanimationPatients(): Patient[] {
  const patients: Patient[] = [
    {
      id: 'p1',
      name: 'Mohammed El Fassi',
      age: 68,
      gender: 'M',
      bed: 'Box 1',
      diagnosis: 'Pneumonie sévère – SDRA',
      comorbidities: ['Diabète type 2', 'HTA', 'BPCO'],
      admissionDate: '18/04/2026',
      physician: 'Pédiatre',
      treatments: ['Antibiotiques IV', 'Ventilation non invasive', 'Insulinothérapie'],
      allergies: ['Pénicilline'],
      vitals: generateVitalHistory(110, 88, 89, 28, 38.9, 13.8, 'Alert'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie veineuse centrale', days: 4, status: 'warning' },
        { type: 'ventilator', name: 'VNI CPAP', days: 2, status: 'normal' },
        { type: 'monitor', name: 'Moniteur multiparamètres', days: 6, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'CRP', value: '215', unit: 'mg/L', status: 'critical' },
        { name: 'Procalcitonine', value: '8.4', unit: 'ng/mL', status: 'critical' },
        { name: 'Lactates', value: '3.1', unit: 'mmol/L', status: 'abnormal' },
        { name: 'Créatinine', value: '142', unit: 'µmol/L', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p2',
      name: 'Fatima Bennani',
      age: 74,
      gender: 'F',
      bed: 'Box 2',
      diagnosis: 'Infarctus du myocarde – Choc cardiogénique',
      comorbidities: ['Coronaropathie', 'Insuffisance cardiaque', 'FA permanente'],
      admissionDate: '19/04/2026',
      physician: 'Pédiatre',
      treatments: ['Dobutamine', 'Héparine', 'Aspirine', 'Défibrillateur implantable'],
      allergies: [],
      vitals: generateVitalHistory(52, 82, 94, 22, 37.2, 6.1, 'Alert'),
      devices: makeDevices([
        { type: 'catheter', name: 'Swan-Ganz', days: 1, status: 'normal' },
        { type: 'pump', name: 'Pompe à dobutamine', days: 1, status: 'normal' },
        { type: 'perfusion', name: 'Héparine IV continue', days: 1, status: 'normal' },
        { type: 'monitor', name: 'ECG continu', days: 1, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Troponine I', value: '8500', unit: 'ng/L', status: 'critical' },
        { name: 'BNP', value: '2340', unit: 'pg/mL', status: 'critical' },
        { name: 'Hémoglobine', value: '10.2', unit: 'g/dL', status: 'abnormal' },
        { name: 'Potassium', value: '4.1', unit: 'mmol/L', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p3',
      name: 'Ahmed Boukhari',
      age: 45,
      gender: 'M',
      bed: 'Box 3',
      diagnosis: 'Traumatisme crânien grave – Polytraumatisme',
      comorbidities: ['Aucun antécédent notable'],
      admissionDate: '20/04/2026',
      physician: 'Pédiatre',
      treatments: ['Sédation-analgésie', 'Ventilation mécanique', 'Osmothérapie'],
      allergies: ['Morphine'],
      vitals: generateVitalHistory(75, 148, 97, 14, 37.0, 7.2, 'Unresponsive'),
      devices: makeDevices([
        { type: 'ventilator', name: 'Ventilation mécanique invasive', days: 0, status: 'normal' },
        { type: 'catheter', name: 'Capteur PIC', days: 0, status: 'normal' },
        { type: 'catheter', name: 'Voie artérielle radiale', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Propofol IV', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Hémoglobine', value: '9.1', unit: 'g/dL', status: 'abnormal' },
        { name: 'INR', value: '1.8', unit: '', status: 'abnormal' },
        { name: 'Natrémie', value: '158', unit: 'mmol/L', status: 'critical' },
        { name: 'Glycémie', value: '7.2', unit: 'mmol/L', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p4',
      name: 'Amina Osman',
      age: 58,
      gender: 'F',
      bed: 'Box 4',
      diagnosis: 'Sepsis sévère – Pyélonéphrite compliquée',
      comorbidities: ['Diabète type 1', 'IRC stade 3'],
      admissionDate: '17/04/2026',
      physician: 'Pédiatre',
      treatments: ['Pipéracilline-Tazobactam', 'Remplissage vasculaire', 'Noradrénaline'],
      allergies: ['Fluoroquinolones'],
      vitals: generateVitalHistory(118, 92, 93, 26, 39.4, 11.2, 'Alert'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie centrale jugulaire', days: 3, status: 'normal' },
        { type: 'pump', name: 'Noradrénaline IV', days: 3, status: 'normal' },
        { type: 'catheter', name: 'Sonde vésicale', days: 7, status: 'error' },
        { type: 'perfusion', name: 'Antibiotiques IV', days: 3, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Lactates', value: '4.2', unit: 'mmol/L', status: 'critical' },
        { name: 'CRP', value: '310', unit: 'mg/L', status: 'critical' },
        { name: 'Créatinine', value: '285', unit: 'µmol/L', status: 'critical' },
        { name: 'Leucocytes', value: '18.5', unit: 'G/L', status: 'critical' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p5',
      name: 'Karim Tazi',
      age: 62,
      gender: 'M',
      bed: 'Box 5',
      diagnosis: 'Post-op chirurgie cardiaque – PAC x3',
      comorbidities: ['Coronaropathie', 'HTA', 'Dyslipidémie'],
      admissionDate: '20/04/2026',
      physician: 'Pédiatre',
      treatments: ['Analgésie IV', 'Bêta-bloquants', 'Héparine bas débit'],
      allergies: [],
      vitals: generateVitalHistory(78, 128, 98, 16, 37.3, 5.8, 'Alert'),
      devices: makeDevices([
        { type: 'catheter', name: 'Drain thoracique', days: 0, status: 'normal' },
        { type: 'monitor', name: 'Moniteur cardiaque', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Analgésie PCA', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Hémoglobine', value: '11.8', unit: 'g/dL', status: 'abnormal' },
        { name: 'CRP', value: '42', unit: 'mg/L', status: 'abnormal' },
        { name: 'Potassium', value: '3.9', unit: 'mmol/L', status: 'normal' },
        { name: 'Créatinine', value: '95', unit: 'µmol/L', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p6',
      name: 'Layla Riad',
      age: 33,
      gender: 'F',
      bed: 'Box 6',
      diagnosis: 'Éclampsie sévère – Post-partum',
      comorbidities: ['Pré-éclampsie connue'],
      admissionDate: '19/04/2026',
      physician: 'Pédiatre',
      treatments: ['Sulfate de magnésium', 'Antihypertenseurs', 'Corticoïdes'],
      allergies: [],
      vitals: generateVitalHistory(95, 168, 96, 18, 37.8, 8.4, 'Alert'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie veineuse périphérique', days: 1, status: 'normal' },
        { type: 'monitor', name: 'Monitoring fœtal', days: 1, status: 'normal' },
        { type: 'catheter', name: 'Sonde urinaire', days: 1, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Plaquettes', value: '88', unit: 'G/L', status: 'critical' },
        { name: 'ASAT', value: '245', unit: 'UI/L', status: 'critical' },
        { name: 'Protéinurie', value: '4.2', unit: 'g/24h', status: 'critical' },
        { name: 'LDH', value: '780', unit: 'UI/L', status: 'critical' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p7',
      name: 'Hassan Khachani',
      age: 71,
      gender: 'M',
      bed: 'Box 7',
      diagnosis: 'Insuffisance respiratoire aiguë – BPCO décompensée',
      comorbidities: ['BPCO stade IV', 'Tabagisme actif', 'Insuffisance cardiaque droite'],
      admissionDate: '19/04/2026',
      physician: 'Pédiatre',
      treatments: ['Bronchodilatateurs nébulisés', 'Corticoïdes IV', 'VNI BiPAP', 'Antibiothérapie'],
      allergies: [],
      vitals: generateVitalHistory(102, 135, 86, 30, 37.6, 6.9, 'Alert'),
      devices: makeDevices([
        { type: 'ventilator', name: 'VNI BiPAP', days: 2, status: 'normal' },
        { type: 'catheter', name: 'Voie veineuse périphérique', days: 2, status: 'normal' },
        { type: 'monitor', name: 'Oxymètre de pouls continu', days: 2, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'PaCO2', value: '68', unit: 'mmHg', status: 'critical' },
        { name: 'pH', value: '7.28', unit: '', status: 'critical' },
        { name: 'HCO3-', value: '31', unit: 'mmol/L', status: 'abnormal' },
        { name: 'CRP', value: '88', unit: 'mg/L', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p8',
      name: 'Noor Alami',
      age: 29,
      gender: 'F',
      bed: 'Box 8',
      diagnosis: 'Acidocétose diabétique sévère',
      comorbidities: ['Diabète type 1 depuis l\'enfance'],
      admissionDate: '20/04/2026',
      physician: 'Pédiatre',
      treatments: ['Insuline IV continue', 'Réhydratation IV', 'Supplémentation potassique'],
      allergies: ['Sulfamides'],
      vitals: generateVitalHistory(108, 102, 97, 24, 37.4, 22.5, 'Alert'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie veineuse centrale', days: 0, status: 'normal' },
        { type: 'pump', name: 'Insuline IV IVSE', days: 0, status: 'normal' },
        { type: 'monitor', name: 'Moniteur glycémique continu', days: 0, status: 'normal' },
        { type: 'catheter', name: 'Sonde urinaire', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Glycémie', value: '28.4', unit: 'mmol/L', status: 'critical' },
        { name: 'Corps cétoniques', value: '6.8', unit: 'mmol/L', status: 'critical' },
        { name: 'pH', value: '7.18', unit: '', status: 'critical' },
        { name: 'Potassium', value: '3.2', unit: 'mmol/L', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p9',
      name: 'Youssef Mansouri',
      age: 55,
      gender: 'M',
      bed: 'Box 9',
      diagnosis: 'Hémorragie digestive haute – Ulcère gastrique perforé',
      comorbidities: ['Éthylisme chronique', 'Cirrhose Child-Pugh B'],
      admissionDate: '18/04/2026',
      physician: 'Pédiatre',
      treatments: ['Inhibiteurs pompe à protons IV', 'Somatostatine', 'Transfusion CGR', 'Vitamine K'],
      allergies: [],
      vitals: generateVitalHistory(125, 78, 95, 20, 37.1, 5.2, 'Voice'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie centrale sous-clavière', days: 2, status: 'normal' },
        { type: 'perfusion', name: 'IPP IV continu', days: 2, status: 'normal' },
        { type: 'catheter', name: 'Sonde nasogastrique', days: 1, status: 'warning' },
        { type: 'monitor', name: 'Moniteur hémodynamique', days: 2, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Hémoglobine', value: '6.8', unit: 'g/dL', status: 'critical' },
        { name: 'INR', value: '2.4', unit: '', status: 'critical' },
        { name: 'Urée', value: '18.2', unit: 'mmol/L', status: 'critical' },
        { name: 'Albumine', value: '24', unit: 'g/L', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'p10',
      name: 'Mariam Qadri',
      age: 48,
      gender: 'F',
      bed: 'Box 10',
      diagnosis: 'Méningite bactérienne – Pneumocoque',
      comorbidities: ['Asplénie post-splénectomie', 'Immunodépression'],
      admissionDate: '20/04/2026',
      physician: 'Pédiatre',
      treatments: ['Ceftriaxone IV', 'Dexaméthasone IV', 'Antiépileptiques', 'Osmotraitement'],
      allergies: ['Amoxicilline'],
      vitals: generateVitalHistory(130, 95, 94, 26, 40.1, 8.8, 'Pain'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie veineuse centrale', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Antibiotiques IV', days: 0, status: 'normal' },
        { type: 'monitor', name: 'EEG continu', days: 0, status: 'normal' },
        { type: 'catheter', name: 'Ponction lombaire – drain', days: 0, status: 'warning' },
      ]),
      biologicalResults: makeBio([
        { name: 'LCR leucocytes', value: '>1000', unit: '/mm³', status: 'critical' },
        { name: 'CRP', value: '380', unit: 'mg/L', status: 'critical' },
        { name: 'Procalcitonine', value: '45', unit: 'ng/mL', status: 'critical' },
        { name: 'Natrémie', value: '128', unit: 'mmol/L', status: 'critical' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'reanimation',
      status: 'admitted',
      patientNumber: 0,
    },
  ];

  return patients.map((p) => {
    const latestVitals = p.vitals[p.vitals.length - 1];
    const newsScore = calculateNEWS(latestVitals);
    const aiInsights = generateAIInsights({ ...p, newsScore }, newsScore);
    return { ...p, newsScore, aiInsights };
  });
}

function createSoinsIntensifPatients(): Patient[] {
  return createReanimationPatients();
}

function createDechocagePatients(): Patient[] {
  const patients: Patient[] = [
    {
      id: 'd1',
      name: 'Tariq Bennani',
      age: 52,
      gender: 'M',
      bed: 'Dechocage 1',
      diagnosis: 'Polytraumatisme – Accident de la route',
      comorbidities: ['HTA'],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Remplissage vasculaire d\'urgence', 'Réanimation cardiopulmonaire', 'Urgence chirurgicale'],
      allergies: [],
      vitals: generateVitalHistory(145, 85, 88, 35, 37.2, 6.5, 'Pain'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie veineuse centrale x2', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Cristalloïdes massifs', days: 0, status: 'normal' },
        { type: 'monitor', name: 'Monitoring intensif', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Hémoglobine', value: '7.2', unit: 'g/dL', status: 'critical' },
        { name: 'Lactates', value: '7.8', unit: 'mmol/L', status: 'critical' },
        { name: 'INR', value: '2.1', unit: '', status: 'critical' },
        { name: 'Plaquettes', value: '45', unit: 'G/L', status: 'critical' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'dechocage',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'd2',
      name: 'Salim Okacha',
      age: 38,
      gender: 'M',
      bed: 'Dechocage 2',
      diagnosis: 'Brûlures graves – 35% SCTI',
      comorbidities: [],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Remplissage selon Parkland', 'Escarrotomies', 'Pansements stériles', 'Antalgiques'],
      allergies: [],
      vitals: generateVitalHistory(138, 92, 91, 32, 38.5, 5.9, 'Alert'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie centrale Swan-Ganz', days: 0, status: 'normal' },
        { type: 'catheter', name: 'Sonde urinaire avec diurèse', days: 0, status: 'normal' },
        { type: 'pump', name: 'Remplissage IV continu', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Hémoglobine', value: '14.2', unit: 'g/dL', status: 'normal' },
        { name: 'Créatinine', value: '156', unit: 'µmol/L', status: 'abnormal' },
        { name: 'Potassium', value: '5.8', unit: 'mmol/L', status: 'critical' },
        { name: 'Myoglobine urinaire', value: 'Élevée', unit: '', status: 'critical' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'dechocage',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'd3',
      name: 'Leila Amara',
      age: 42,
      gender: 'F',
      bed: 'Dechocage 3',
      diagnosis: 'Choc septique – Urgence abdominale',
      comorbidities: [],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Antibiotiques large spectre', 'Noradrénaline', 'Remplissage vasculaire', 'Urgence OR'],
      allergies: ['Céphalosporines'],
      vitals: generateVitalHistory(155, 72, 87, 38, 39.8, 4.8, 'Voice'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie veineuse centrale x2', days: 0, status: 'normal' },
        { type: 'pump', name: 'Noradrénaline IV', days: 0, status: 'normal' },
        { type: 'catheter', name: 'Sonde urinaire', days: 0, status: 'normal' },
        { type: 'monitor', name: 'Moniteur hémodynamique', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Lactates', value: '9.2', unit: 'mmol/L', status: 'critical' },
        { name: 'Leucocytes', value: '22.5', unit: 'G/L', status: 'critical' },
        { name: 'Thrombopénie', value: '78', unit: 'G/L', status: 'critical' },
        { name: 'CRP', value: '450', unit: 'mg/L', status: 'critical' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'dechocage',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'd4',
      name: 'Rashid Khalil',
      age: 67,
      gender: 'M',
      bed: 'Dechocage 4',
      diagnosis: 'Syndrome coronarien aigu – Choc cardiogénique',
      comorbidities: ['Diabète', 'HTA'],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Angioplastie d\'urgence', 'Dobutamine', 'Ballon intra-aortique', 'Antiplatéens'],
      allergies: [],
      vitals: generateVitalHistory(105, 75, 92, 28, 37.4, 8.1, 'Alert'),
      devices: makeDevices([
        { type: 'catheter', name: 'Cathéter Swan-Ganz', days: 0, status: 'normal' },
        { type: 'pump', name: 'Dobutamine IV', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Héparine IV continue', days: 0, status: 'normal' },
        { type: 'monitor', name: 'ECG continu + troponine', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Troponine', value: '12000', unit: 'ng/L', status: 'critical' },
        { name: 'BNP', value: '3200', unit: 'pg/mL', status: 'critical' },
        { name: 'INR', value: '2.8', unit: '', status: 'critical' },
        { name: 'Créatinine', value: '178', unit: 'µmol/L', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'dechocage',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'd5',
      name: 'Zahra Filali',
      age: 35,
      gender: 'F',
      bed: 'Dechocage 5',
      diagnosis: 'Embolie pulmonaire massive – Choc',
      comorbidities: ['Thrombophilie'],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Thrombolyse IV d\'urgence', 'Anticoagulation', 'O2 haute concentration', 'Remplissage'],
      allergies: [],
      vitals: generateVitalHistory(168, 88, 82, 40, 37.9, 6.2, 'Pain'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie veineuse centrale', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Thrombolyse IV', days: 0, status: 'normal' },
        { type: 'monitor', name: 'ECG + capnographie', days: 0, status: 'normal' },
        { type: 'ventilator', name: 'O2 masque réservoir', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'D-Dimères', value: '>5000', unit: 'µg/L', status: 'critical' },
        { name: 'Troponine', value: '2850', unit: 'ng/L', status: 'critical' },
        { name: 'BNP', value: '2100', unit: 'pg/mL', status: 'critical' },
        { name: 'Lactates', value: '6.5', unit: 'mmol/L', status: 'critical' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'dechocage',
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'd6',
      name: 'Hassan Chakib',
      age: 28,
      gender: 'M',
      bed: 'Dechocage 6',
      diagnosis: 'Tentative de suicide – Intoxication médicamenteuse',
      comorbidities: [],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Lavage gastrique', 'Charbon activé', 'Antidotes selon toxique', 'Soutien hémodynamique'],
      allergies: [],
      vitals: generateVitalHistory(92, 94, 85, 18, 36.8, 5.1, 'Unresponsive'),
      devices: makeDevices([
        { type: 'catheter', name: 'Voie veineuse centrale', days: 0, status: 'normal' },
        { type: 'catheter', name: 'Sonde nasogastrique', days: 0, status: 'normal' },
        { type: 'ventilator', name: 'VNI d\'assistance', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Soutien pharmacologique', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Osmolarité', value: '315', unit: 'mOsm/kg', status: 'critical' },
        { name: 'pH sanguin', value: '7.18', unit: '', status: 'critical' },
        { name: 'Glucose', value: '45', unit: 'mg/dL', status: 'critical' },
        { name: 'Ammoniémie', value: '185', unit: 'µmol/L', status: 'critical' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'dechocage',
      status: 'admitted',
      patientNumber: 0,
    },
  ];

  return patients.map((p) => {
    const latestVitals = p.vitals[p.vitals.length - 1];
    const newsScore = calculateNEWS(latestVitals);
    const aiInsights = generateAIInsights({ ...p, newsScore }, newsScore);
    return { ...p, newsScore, aiInsights };
  });
}

function createNeonatologiePatients(): Patient[] {
  const patients: Patient[] = [
    // Boxes 1-5: Nouveau-nés à terme
    {
      id: 'neo1',
      name: 'Nouara (BB de Samira)',
      age: 0,
      gender: 'F',
      bed: 'Neo Box 1',
      diagnosis: 'Nouveau-né à terme sain – Surveillance post-natale',
      comorbidities: [],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Allaitement', 'Photothérapie prophylactique', 'Surveillance thermostatée'],
      allergies: [],
      vitals: generateNeoVitalHistory(138, 96, 48, 37.2, 3450, false, 9) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Table chauffante thermostatée', days: 0, status: 'normal' },
        { type: 'monitor', name: 'Photothérapie LED', days: 0, status: 'normal' },
        { type: 'monitor', name: 'Oxymètre pulsé', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Bilirubinémie', value: '8.2', unit: 'mg/dL', status: 'normal' },
        { name: 'Glycémie', value: '0.87', unit: 'g/l', status: 'normal' },
        { name: 'Calcium', value: '8.9', unit: 'mg/dL', status: 'normal' },
        { name: 'Hémoglobine', value: '16.5', unit: 'g/dL', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'neo2',
      name: 'Karim Jr (BB de Nour)',
      age: 0,
      gender: 'M',
      bed: 'Neo Box 2',
      diagnosis: 'Nouveau-né à terme – Ictère physiologique',
      comorbidities: [],
      admissionDate: '20/04/2026',
      physician: 'Pédiatre',
      treatments: ['Photothérapie intensive', 'Alimentation toutes les 2h', 'Surveillance bilirubin'],
      allergies: [],
      vitals: generateNeoVitalHistory(145, 95, 50, 37.0, 3680, false, 8) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Table chauffante', days: 1, status: 'normal' },
        { type: 'monitor', name: 'Photothérapie triple LED', days: 1, status: 'normal' },
        { type: 'perfusion', name: 'Sonde nasogastrique', days: 1, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Bilirubinémie', value: '14.2', unit: 'mg/dL', status: 'abnormal' },
        { name: 'Glycémie', value: '0.94', unit: 'g/l', status: 'normal' },
        { name: 'pH', value: '7.32', unit: '', status: 'normal' },
        { name: 'Hématocrite', value: '52', unit: '%', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'neo3',
      name: 'Amira (BB de Zahia)',
      age: 1,
      gender: 'F',
      bed: 'Neo Box 3',
      diagnosis: 'Détresse respiratoire transitoire',
      comorbidities: [],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['O2 par lunettes nasales', 'CPAP si dégradation', 'Surveillance FR'],
      allergies: [],
      vitals: generateNeoVitalHistory(155, 92, 58, 37.4, 3200, false, 7) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Table chauffante', days: 0, status: 'normal' },
        { type: 'monitor', name: 'O2 mètre', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Lunettes O2 bas débit', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'PaO2', value: '55', unit: 'mmHg', status: 'abnormal' },
        { name: 'PaCO2', value: '48', unit: 'mmHg', status: 'normal' },
        { name: 'Glycémie', value: '0.81', unit: 'g/l', status: 'normal' },
        { name: 'Bilirubinémie', value: '6.5', unit: 'mg/dL', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'neo4',
      name: 'Zain (BB de Layla)',
      age: 2,
      gender: 'M',
      bed: 'Neo Box 4',
      diagnosis: 'Syndrome d\'aspiration de méconium – Surveillance étroite',
      comorbidities: [],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Surveillance étroite', 'O2 disponible', 'Succion trachéale si besoin'],
      allergies: [],
      vitals: generateNeoVitalHistory(142, 94, 52, 36.9, 3750, false, 7) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Table chauffante', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Accès IV de secours', days: 0, status: 'normal' },
        { type: 'monitor', name: 'Oxymètre continu', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Gazométrie', value: 'normale', unit: '', status: 'normal' },
        { name: 'Hémoglobine', value: '17.2', unit: 'g/dL', status: 'normal' },
        { name: 'Glycémie', value: '0.90', unit: 'g/l', status: 'normal' },
        { name: 'Bilirubinémie', value: '5.8', unit: 'mg/dL', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'neo5',
      name: 'Yasmine (BB de Hana)',
      age: 3,
      gender: 'F',
      bed: 'Neo Box 5',
      diagnosis: 'Hypoglycémie néonatale – Traitement en cours',
      comorbidities: ['Mère diabétique'],
      admissionDate: '21/04/2026',
      physician: 'Pédiatre',
      treatments: ['Dextrose IV', 'Surveillance glycémie', 'Allaitement renforcé'],
      allergies: [],
      vitals: generateNeoVitalHistory(128, 93, 46, 37.1, 2890, false, 8) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Table chauffante', days: 0, status: 'normal' },
        { type: 'perfusion', name: 'Glucose IV', days: 0, status: 'normal' },
        { type: 'monitor', name: 'Glucomètre de secours', days: 0, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'Glycémie', value: '0.68', unit: 'g/l', status: 'abnormal' },
        { name: 'Calcium', value: '8.2', unit: 'mg/dL', status: 'abnormal' },
        { name: 'Bilirubinémie', value: '7.1', unit: 'mg/dL', status: 'normal' },
        { name: 'pH', value: '7.28', unit: '', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    // Boxes 6-10: Grands prématurés
    {
      id: 'neo6',
      name: 'Aaliyah (BB prématuré)',
      age: 0,
      gender: 'F',
      bed: 'Neo Box 6 – Coveuse 1',
      diagnosis: 'Grand prématuré 32 SA – Retard de croissance intra-utérin – Surveillance intensive',
      comorbidities: ['Hypothermie', 'Immaturité pulmonaire'],
      admissionDate: '18/04/2026',
      physician: 'Pédiatre',
      treatments: ['Coveuse contrôlée 36.5°C', 'Surfactant IV', 'VNI CPAP', 'Nutrition parentérale'],
      allergies: [],
      vitals: generateNeoVitalHistory(160, 88, 55, 36.8, 1680, true, 5) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Coveuse fermée thermostatée', days: 3, status: 'normal' },
        { type: 'monitor', name: 'CPAP nasal', days: 3, status: 'normal' },
        { type: 'perfusion', name: 'Nutrition parentérale TPN', days: 3, status: 'normal' },
        { type: 'monitor', name: 'Photothérapie LED', days: 3, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'PaO2', value: '62', unit: 'mmHg', status: 'abnormal' },
        { name: 'PaCO2', value: '52', unit: 'mmHg', status: 'abnormal' },
        { name: 'Glucose', value: '0.76', unit: 'g/l', status: 'normal' },
        { name: 'Calcium', value: '7.8', unit: 'mg/dL', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'neo7',
      name: 'Ibrahim (BB prématuré)',
      age: 1,
      gender: 'M',
      bed: 'Neo Box 7 – Coveuse 2',
      diagnosis: 'Prématuré extrême 29 SA – Syndrome de détresse respiratoire – Ventilation mécanique',
      comorbidities: ['Apnées du prématuré', 'Bradycardies'],
      admissionDate: '19/04/2026',
      physician: 'Pédiatre',
      treatments: ['Ventilation mécanique SIMV', 'Caféine', 'Monitoring cardiaque ECG', 'Dextrose IV'],
      allergies: [],
      vitals: generateNeoVitalHistory(175, 85, 62, 36.5, 1420, true, 3) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Coveuse ouverte avec sonde réchauffée', days: 2, status: 'normal' },
        { type: 'ventilator', name: 'Ventilateur SIMV néonatal', days: 2, status: 'normal' },
        { type: 'monitor', name: 'Monitoring cardiaque continu', days: 2, status: 'warning' },
        { type: 'perfusion', name: 'Ligne ombilicale + TPN', days: 2, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'PaO2', value: '48', unit: 'mmHg', status: 'critical' },
        { name: 'PaCO2', value: '58', unit: 'mmHg', status: 'critical' },
        { name: 'Bilirubinémie', value: '12.5', unit: 'mg/dL', status: 'critical' },
        { name: 'Glucose', value: '0.58', unit: 'g/l', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'neo8',
      name: 'Layan (BB prématuré)',
      age: 2,
      gender: 'F',
      bed: 'Neo Box 8 – Coveuse 3',
      diagnosis: 'Extrême prématuré 26 SA – Hémorragie intra-ventriculaire – Lésions cérébrales',
      comorbidities: ['Leucomalacie périventriculaire', 'Hémorragie intra-ventriculaire grade II'],
      admissionDate: '15/04/2026',
      physician: 'Pédiatre',
      treatments: ['Ventilation HFO', 'Surfactant répétés', 'Indométacine', 'Supports hémodynamiques'],
      allergies: [],
      vitals: generateNeoVitalHistory(182, 82, 68, 36.2, 820, true, 2) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Coveuse fermée intensif', days: 6, status: 'normal' },
        { type: 'ventilator', name: 'Ventilateur haute fréquence oscillante', days: 6, status: 'warning' },
        { type: 'monitor', name: 'EEG de surveillance', days: 3, status: 'normal' },
        { type: 'perfusion', name: 'Voies centrales x2 + TPN', days: 6, status: 'warning' },
      ]),
      biologicalResults: makeBio([
        { name: 'PaO2', value: '42', unit: 'mmHg', status: 'critical' },
        { name: 'PaCO2', value: '65', unit: 'mmHg', status: 'critical' },
        { name: 'Bilirubinémie', value: '18.2', unit: 'mg/dL', status: 'critical' },
        { name: 'Plaquettes', value: '82', unit: 'G/L', status: 'abnormal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'neo9',
      name: 'Rashid Jr (BB prématuré)',
      age: 5,
      gender: 'M',
      bed: 'Neo Box 9 – Coveuse 4',
      diagnosis: 'Prématuré 30 SA – Entérocolite ulcéro-nécrosante – Alimentation suspendue',
      comorbidities: ['Apnées', 'Alimentation limitée'],
      admissionDate: '16/04/2026',
      physician: 'Pédiatre',
      treatments: ['Jeûne 10 jours', 'Antibiotiques large spectre', 'TPN exclusive', 'Monitoring abdo'],
      allergies: [],
      vitals: generateNeoVitalHistory(165, 87, 58, 37.0, 1550, true, 5) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Coveuse', days: 5, status: 'normal' },
        { type: 'monitor', name: 'CPAP nasal', days: 5, status: 'normal' },
        { type: 'perfusion', name: 'Nutrition parentérale', days: 5, status: 'normal' },
        { type: 'catheter', name: 'Sonde nasogastrique', days: 5, status: 'warning' },
      ]),
      biologicalResults: makeBio([
        { name: 'CRP', value: '42', unit: 'mg/L', status: 'abnormal' },
        { name: 'Leucocytes', value: '12.5', unit: 'G/L', status: 'abnormal' },
        { name: 'Glycémie', value: '0.85', unit: 'g/l', status: 'normal' },
        { name: 'Créatinine', value: '0.8', unit: 'mg/dL', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
    {
      id: 'neo10',
      name: 'Maryam (BB prématuré)',
      age: 4,
      gender: 'F',
      bed: 'Neo Box 10 – Coveuse 5',
      diagnosis: 'Prématuré 31 SA – Rétinopathie du prématuré – Oxygène-dépendance',
      comorbidities: ['O2-dépendance', 'RDP progressive'],
      admissionDate: '17/04/2026',
      physician: 'Pédiatre',
      treatments: ['O2 contrôlé SpO2 90-95%', 'Alimentation progressive', 'Dépistage RDP mensuel'],
      allergies: [],
      vitals: generateNeoVitalHistory(150, 90, 61, 37.2, 1780, true, 6) as any,
      devices: makeDevices([
        { type: 'monitor', name: 'Coveuse', days: 4, status: 'normal' },
        { type: 'monitor', name: 'O2 humidifié', days: 4, status: 'normal' },
        { type: 'perfusion', name: 'Nutrition entérale progressive', days: 2, status: 'normal' },
        { type: 'monitor', name: 'Ophtalmoscope de dépistage RDP', days: 1, status: 'normal' },
      ]),
      biologicalResults: makeBio([
        { name: 'PaO2', value: '75', unit: 'mmHg', status: 'normal' },
        { name: 'Hémoglobine', value: '14.2', unit: 'g/dL', status: 'normal' },
        { name: 'Glycémie', value: '0.88', unit: 'g/l', status: 'normal' },
        { name: 'Calcium', value: '8.5', unit: 'mg/dL', status: 'normal' },
      ]),
      aiInsights: [],
      newsScore: emptyNews,
      service: 'neonatologie',
      isNeonatal: true,
      status: 'admitted',
      patientNumber: 0,
    },
  ];

  return patients.map((p) => {
    const latestVitals = p.vitals[p.vitals.length - 1];
    const newsScore = calculateNEWS(latestVitals);
    const aiInsights = generateAIInsights({ ...p, newsScore }, newsScore);
    return { ...p, newsScore, aiInsights };
  });
}
